In [2]:
import os
import shutil

def copy_gh_files(source_folder, destination_folder):
    # Walk through all subfolders in the source folder
    for root, dirs, files in os.walk(source_folder):
        for file in files:
            # Check if the file has a .gh extension
            if file.endswith(".gh"):
                # Construct the full file paths
                source_file = os.path.join(root, file)
                destination_file = os.path.join(destination_folder, file)
                
                try:
                    # Copy the file from the source to the destination
                    shutil.copy2(source_file, destination_file)
                    print(f"Copied: {source_file} -> {destination_file}")
                except IOError as e:
                    print(f"Error copying file: {source_file}. {str(e)}")
                except Exception as e:
                    print(f"Unexpected error occurred while copying file: {source_file}. {str(e)}")
src = r"C:\Users\jossi\Dropbox\Office_Work\Jos\GH_Graph_Learning\Junichira GrasshopperHowtos-master"
dst = r"C:\Users\jossi\Dropbox\Office_Work\Jos\GH_Graph_Learning\ExtractionEnvironments\240318-initial parsing\03-GH_Files\03a-Raw"


In [1]:
import numpy as np
import networkx as nx
def one_hot_on_attribute(G, attribute:str):
    """
    Create a one hot encoding where the mapping dictionary determines the column index of the one hot encoding. 
    The rows represent each node in the graph. The attribute is the node information that we want to categorise.
    
    Parameters:
    G (nx.Graph or nx.DiGraph): The graph to be processed.
    attribute (str): The attribute of the node to be categorised.
    
    Returns:
    np.array: A one hot encoding of the node attributes.
    
    Example:
     G = nx.Graph()
     blue, orange, green = "#1f77b4", "#ff7f0e","#2ca02c"
     G.add_nodes_from([(1, {"color": blue}),
                       (2, {"color": orange}),
                       (3, {"color": blue}),
                       (4, {"color": green})])
     G.add_edges_from([(1, 2),(2, 3),(1, 3),(3, 4)])
     one_hot_encoding = one_hot_on_attribute(G, 'color')
     print(one_hot_encoding)
    [[1. 0. 0.]
     [0. 1. 0.]
     [1. 0. 0.]
     [0. 0. 1.]]
    """
    set_attributes = {v:i for i, v in enumerate(set(nx.get_node_attributes(G, 'color').values()))}
    one_hot_idx = np.array([set_attributes[v] for v in nx.get_node_attributes(G, attribute).values()])
    one_hot_encoding = np.zeros((one_hot_idx.size, len(set_attributes)))
    one_hot_encoding[np.arange(one_hot_idx.size), one_hot_idx] = 1
    return one_hot_encoding

In [1]:
import torch
from IPython.display import display, Latex

def tensor_to_latex_inline(tensor):
    if tensor.dim() == 1:
        tensor = tensor.view(-1, 1)  # Convert to a 2D column vector
    latex_str = "\\left(\\begin{array}{c}"
    for i, row in enumerate(tensor):
        row_str = " & ".join(map('{:.2f}'.format, row.tolist()))
        latex_str += row_str
        if i < tensor.size(0) - 1:
            latex_str += "\\\\"
    latex_str += "\\end{array}\\right)"
    return latex_str

def display_tensors_and_operations_inline(*args):
    latex_expression = "$"
    for arg in args:
        if isinstance(arg, torch.Tensor):
            latex_expression += tensor_to_latex_inline(arg)
        elif isinstance(arg, str):
            latex_expression += arg  # Assume it's a LaTeX compatible operation symbol
        else:
            raise ValueError("Unsupported type. Inputs must be either torch.Tensor or str.")
    latex_expression += "$"
    display(Latex(latex_expression))

# Example tensors
X = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
W1 = torch.tensor([[0.5, -1], [-1.5, 1]], dtype=torch.float32)
A = torch.tensor([[1, 0], [0, 1]], dtype=torch.float32)  # Example adjacency matrix
W2 = torch.tensor([[1.5, 2.5], [0, -0.5]], dtype=torch.float32)
b = torch.tensor([1.0, -1], dtype=torch.float32)  # Bias as a vector

# Display the equation using the function
display_tensors_and_operations_inline(X, '\\times', W1, '+', A, '\\times', X, '\\times', W2, '+', b)


<IPython.core.display.Latex object>